/* -------------------------------------------------------------------------- */
/*                           Tipos del reductor Chat                          */
/* -------------------------------------------------------------------------- */

export const CHAT_USER_MESSAGES_FETCH_STARTED = 'CHAT_USER_MESSAGES_FETCH_STARTED';
export const CHAT_USER_MESSAGES_FETCH_COMPLETED = 'CHAT_USER_MESSAGES_FETCH_COMPLETED';
export const CHAT_USER_MESSAGES_FETCH_FAILED = 'CHAT_USER_MESSAGES_FETCH_FAILED';

export const CHAT_MESSAGES_FETCH_STARTED = 'CHAT_MESSAGES_FETCH_STARTED';
export const CHAT_MESSAGES_FETCH_COMPLETED = 'CHAT_MESSAGES_FETCH_COMPLETED';
export const CHAT_MESSAGES_FETCH_FAILED = 'CHAT_MESSAGES_FETCH_FAILED';
export const CHAT_MESSAGES_CLEAR = 'CHAT_MESSAGES_CLEAR';

export const CHAT_USER_MESSAGES_ADD_STARTED = 'CHAT_USER_MESSAGES_ADD_STARTED';
export const CHAT_USER_MESSAGES_ADD_COMPLETED = 'CHAT_USER_MESSAGES_ADD_COMPLETED';
export const CHAT_USER_MESSAGES_ADD_FAILED = 'CHAT_USER_MESSAGES_ADD_FAILED';

export const CHAT_USER_MESSAGES_UPDATE = 'CHAT_USER_MESSAGES_UPDATE';

export const CHAT_MESSAGES_ADD_STARTED = 'CHAT_MESSAGES_ADD_STARTED';
export const CHAT_MESSAGES_ADD_COMPLETED = 'CHAT_MESSAGES_ADD_COMPLETED';
export const CHAT_MESSAGES_ADD_FAILED = 'CHAT_MESSAGES_ADD_FAILED';

export const CHAT_USER_MESSAGES_SELECT = 'CHAT_USER_MESSAGES_SELECT';
export const CHAT_USER_MESSAGES_DESELECT = 'CHAT_USER_MESSAGES_DESELECT';
