/* -------------------------------------------------------------------------- */
/*                      Tipos del reductor Notifications                      */
/* -------------------------------------------------------------------------- */

export const NOTIFICATIONS_RETWEETS_FETCH_STARTED = 'NOTIFICATIONS_RETWEETS_FETCH_STARTED';
export const NOTIFICATIONS_RETWEETS_FETCH_COMPLETED = 'NOTIFICATIONS_RETWEETS_FETCH_COMPLETED';
export const NOTIFICATIONS_RETWEETS_FETCH_FAILED = 'NOTIFICATIONS_RETWEETS_FETCH_FAILED';
export const NOTIFICATIONS_RETWEETS_CLEAR = 'NOTIFICATIONS_RETWEETS_CLEAR';

export const NOTIFICATIONS_COMMENTS_FETCH_STARTED = 'NOTIFICATIONS_COMMENTS_FETCH_STARTED';
export const NOTIFICATIONS_COMMENTS_FETCH_COMPLETED = 'NOTIFICATIONS_COMMENTS_FETCH_COMPLETED';
export const NOTIFICATIONS_COMMENTS_FETCH_FAILED = 'NOTIFICATIONS_COMMENTS_FETCH_FAILED';
export const NOTIFICATIONS_COMMENTS_CLEAR = 'NOTIFICATIONS_COMMENTS_CLEAR';

export const NOTIFICATIONS_LIKES_FETCH_STARTED = 'NOTIFICATIONS_LIKES_FETCH_STARTED';
export const NOTIFICATIONS_LIKES_FETCH_COMPLETED = 'NOTIFICATIONS_LIKES_FETCH_COMPLETED';
export const NOTIFICATIONS_LIKES_FETCH_FAILED = 'NOTIFICATIONS_LIKES_FETCH_FAILED';
export const NOTIFICATIONS_LIKES_CLEAR = 'NOTIFICATIONS_LIKES_CLEAR';
