export const PROFILE_USER_ID_SELECTED = 'PROFILE_USER_ID_SELECTED';

export const PROFILE_INFO_FETCH_STARTED = 'PROFILE_INFO_FETCH_STARTED';
export const PROFILE_INFO_FETCH_COMPLETED = 'PROFILE_INFO_FETCH_COMPLETED';
export const PROFILE_INFO_FETCH_FAILED = 'PROFILE_INFO_FETCH_FAILED';

export const PROFILE_FOLLOWERS_FETCH_STARTED = 'PROFILE_FOLLOWERS_FETCH_STARTED';
export const PROFILE_FOLLOWERS_FETCH_COMPLETED = 'PROFILE_FOLLOWERS_FETCH_COMPLETED';
export const PROFILE_FOLLOWERS_FETCH_FAILED = 'PROFILE_FOLLOWERS_FETCH_FAILED';

export const PROFILE_FOLLOWING_FETCH_STARTED = 'PROFILE_FOLLOWING_FETCH_STARTED';
export const PROFILE_FOLLOWING_FETCH_COMPLETED = 'PROFILE_FOLLOWING_FETCH_COMPLETED';
export const PROFILE_FOLLOWING_FETCH_FAILED = 'PROFILE_FOLLOWING_FETCH_FAILED';

export const PROFILE_MY_TWEETS_FETCH_STARTED = 'PROFILE_MY_TWEETS_FETCH_STARTED';
export const PROFILE_MY_TWEETS_FETCH_COMPLETED = 'PROFILE_MY_TWEETS_FETCH_COMPLETED';
export const PROFILE_MY_TWEETS_FETCH_FAILED = 'PROFILE_MY_TWEETS_FETCH_FAILED';

export const PROFILE_LIKED_TWEETS_FETCH_STARTED = 'PROFILE_LIKED_TWEETS_FETCH_STARTED';
export const PROFILE_LIKED_TWEETS_FETCH_COMPLETED = 'PROFILE_LIKED_TWEETS_FETCH_COMPLETED';
export const PROFILE_LIKED_TWEETS_FETCH_FAILED = 'PROFILE_LIKED_TWEETS_FETCH_FAILED';
