
export const SEARCH_USERS_FETCH_STARTED = 'SEARCH_USERS_FETCH_STARTED';
export const SEARCH_USERS_FETCH_COMPLETED = 'SEARCH_USERS_FETCH_COMPLETED';
export const SEARCH_USERS_FETCH_FAILED = 'SEARCH_USERS_FETCH_FAILED';
export const SEARCH_USERS_CLEAR = 'SEARCH_USERS_CLEAR';

export const SEARCH_TWEETS_FETCH_STARTED = 'SEARCH_TWEETS_FETCH_STARTED';
export const SEARCH_TWEETS_FETCH_COMPLETED = 'SEARCH_TWEETS_FETCH_COMPLETED';
export const SEARCH_TWEETS_FETCH_FAILED = 'SEARCH_TWEETS_FETCH_FAILED';
export const SEARCH_TWEETS_CLEAR = 'SEARCH_TWEETS_CLEAR';
