export const TWEETS_HOME_FETCH_STARTED = 'TWEETS_FETCH_STARTED';
export const TWEETS_HOME_FETCH_COMPLETED = 'TWEETS_FETCH_COMPLETED';
export const TWEETS_HOME_FETCH_FAILED = 'TWEETS_FETCH_FAILED';

export const TWEET_ADD_STARTED = 'TWEET_ADD_STARTED';
export const TWEET_ADD_COMPLETED = 'TWEET_ADD_COMPLETED';
export const TWEET_ADD_FAILED = 'TWEET_ADD_FAILED';

export const TWEET_REMOVE_STARTED = 'TWEET_REMOVE_STARTED';
export const TWEET_REMOVE_COMPLETED = 'TWEET_REMOVE_COMPLETED';
export const TWEET_REMOVE_FAILED = 'TWEET_REMOVE_FAILED';


export const TWEET_LIKE_STARTED = 'TWEET_LIKE_STARTED';
export const TWEET_LIKE_COMPLETED = 'TWEET_LIKE_COMPLETED';
export const TWEET_LIKE_FAILED = 'TWEET_LIKE_FAILED';

export const TWEET_RETWEET_STARTED = 'TWEET_RETWEET_STARTED';
export const TWEET_RETWEET_COMPLETED = 'TWEET_RETWEET_COMPLETED';
export const TWEET_RETWEET_FAILED = 'TWEET_RETWEET_FAILED';

export const TWEET_SAVE_TWEET_STARTED = 'TWEET_SAVE_TWEET_STARTED';
export const TWEET_SAVE_TWEET_COMPLETED = 'TWEET_SAVE_TWEET_COMPLETED';
export const TWEET_SAVE_TWEET_FAILED = 'TWEET_SAVE_TWEET_FAILED';


export const TWEET_COMMENT_STARTED = 'TWEET_COMMENT_STARTED';
export const TWEET_COMMENT_COMPLETED = 'TWEET_COMMENT_COMPLETED';
export const TWEET_COMMENT_FAILED = 'TWEET_COMMENT_FAILED';


export const TWEET_FOLLOW_STARTED = 'TWEET_FOLLOW_STARTED';
export const TWEET_FOLLOW_COMPLETED = 'TWEET_FOLLOW_COMPLETED';
export const TWEET_FOLLOW_FAILED = 'TWEET_FOLLOW_FAILED';