export const TWEET_ID_SELECTED = 'TWEET_ID_SELECTED';

export const TWEET_INFO_FETCH_STARTED = 'TWEET_INFO_FETCH_STARTED';
export const TWEET_INFO_FETCH_COMPLETED = 'TWEET_INFO_FETCH_COMPLETED';
export const TWEET_INFO_FETCH_FAILED = 'TWEET_INFO_FETCH_FAILED';

export const TWEET_COMMENT_ADD_STARTED = 'TWEET_COMMENT_ADD_STARTED';
export const TWEET_COMMENT_ADD_COMPLETED = 'TWEET_COMMENT_ADD_COMPLETED';
export const TWEET_COMMENT_ADD_FAILED = 'TWEET_COMMENT_ADD_FAILED';

export const TWEET_COMMENT_REMOVE_STARTED = 'TWEET_COMMENT_REMOVE_STARTED';
export const TWEET_COMMENT_REMOVE_COMPLETED = 'TWEET_COMMENT_REMOVE_COMPLETED';
export const TWEET_COMMENT_REMOVE_FAILED = 'TWEET_COMMENT_REMOVE_FAILED';

export const TWEET_COMMENTS_FETCH_STARTED = 'TWEET_COMMENTS_FETCH_STARTED';
export const TWEET_COMMENTS_FETCH_COMPLETED = 'TWEET_COMMENTS_FETCH_COMPLETED';
export const TWEET_COMMENTS_FETCH_FAILED = 'TWEET_COMMENTS_FETCH_FAILED';

export const TWEET_LIKES_USERS_FETCH_STARTED = 'TWEET_LIKES_USERS_FETCH_STARTED';
export const TWEET_LIKES_USERS_FETCH_COMPLETED = 'TWEET_LIKES_USERS_FETCH_COMPLETED';
export const TWEET_LIKES_USERS_FETCH_FAILED = 'TWEET_LIKES_USERS_FETCH_FAILED';

export const TWEET_RETWEETS_USERS_FETCH_STARTED = 'TWEET_RETWEETS_USERS_FETCH_STARTED';
export const TWEET_RETWEETS_USERS_FETCH_COMPLETED = 'TWEET_RETWEETS_USERS_FETCH_COMPLETED';
export const TWEET_RETWEETS_USERS_FETCH_FAILED = 'TWEET_RETWEETS_USERS_FETCH_FAILED';
