export const TWEETS_HOME_FETCH_STARTED = 'TWEETS_FETCH_STARTED';
export const TWEETS_HOME_FETCH_COMPLETED = 'TWEETS_FETCH_COMPLETED';
export const TWEETS_HOME_FETCH_FAILED = 'TWEETS_FETCH_FAILED';

export const TWEET_ADD_STARTED = 'TWEET_ADD_STARTED';
export const TWEET_ADD_COMPLETED = 'TWEET_ADD_COMPLETED';
export const TWEET_ADD_FAILED = 'TWEET_ADD_FAILED';

export const TWEET_REMOVE_STARTED = 'TWEET_REMOVE_STARTED';
export const TWEET_REMOVE_COMPLETED = 'TWEET_REMOVE_COMPLETED';
export const TWEET_REMOVE_FAILED = 'TWEET_REMOVE_FAILED';
